title: Alexandra Murariu
description: "Hitchhiking Through Data and AI <br> MSc Student, Data Engineer, Quantum Computing enthusiast <br> Co-founder of Astrocrew 🌌"
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
